// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQngMoNwRaP-3xn20_Vz1jc5KDilJqgK8',
    appId: '1:247175928678:web:12b59e399a66da6deb86a7',
    messagingSenderId: '247175928678',
    projectId: 'rabatlink',
    authDomain: 'rabatlink.firebaseapp.com',
    storageBucket: 'rabatlink.firebasestorage.app',
    measurementId: 'G-YLEJ8K383C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOLQHnCBpPtaA1cA2lko7ZpIhD2u1-fdc',
    appId: '1:247175928678:android:3b8f240cabe7fc0feb86a7',
    messagingSenderId: '247175928678',
    projectId: 'rabatlink',
    storageBucket: 'rabatlink.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYeMEqoZCGVQOCtMScAw4WjrFC6vW4N8',
    appId: '1:247175928678:ios:33eb0df29662ad38eb86a7',
    messagingSenderId: '247175928678',
    projectId: 'rabatlink',
    storageBucket: 'rabatlink.firebasestorage.app',
    iosBundleId: 'com.example.rabatlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxYeMEqoZCGVQOCtMScAw4WjrFC6vW4N8',
    appId: '1:247175928678:ios:33eb0df29662ad38eb86a7',
    messagingSenderId: '247175928678',
    projectId: 'rabatlink',
    storageBucket: 'rabatlink.firebasestorage.app',
    iosBundleId: 'com.example.rabatlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQngMoNwRaP-3xn20_Vz1jc5KDilJqgK8',
    appId: '1:247175928678:web:ea41e8ac424a8ffaeb86a7',
    messagingSenderId: '247175928678',
    projectId: 'rabatlink',
    authDomain: 'rabatlink.firebaseapp.com',
    storageBucket: 'rabatlink.firebasestorage.app',
    measurementId: 'G-MJJG2GY86B',
  );
}
